-- Modelo normalizado para APP/Banco_de_dados/t.sql.
-- Execute no SQL Editor do Supabase antes de importar t-relacional.sql.

create table if not exists niveis (
  id bigint generated by default as identity primary key,
  nome text not null unique
);

create table if not exists tipos_curso (
  id bigint generated by default as identity primary key,
  nivel_id bigint not null references niveis(id),
  nome text not null,
  unique (nivel_id, nome)
);

create table if not exists cursos (
  id bigint generated by default as identity primary key,
  tipo_curso_id bigint not null references tipos_curso(id),
  nome text not null,
  unique (tipo_curso_id, nome)
);

create table if not exists docentes (
  id bigint generated by default as identity primary key,
  registro text unique,
  nome text not null unique,
  area text
);

create table if not exists componentes_curriculares (
  id bigint generated by default as identity primary key,
  sigla text not null,
  nome text not null,
  unique (sigla, nome)
);

create table if not exists turmas (
  id bigint generated by default as identity primary key,
  curso_id bigint not null references cursos(id),
  codigo text not null unique,
  nome text not null default '',
  carga_horaria integer not null check (carga_horaria > 0),
  turno text not null,
  situacao text not null,
  horario_inicio time,
  horario_fim time,
  periodo_inicio date,
  periodo_fim date,
  check (horario_fim is null or horario_inicio is null or horario_fim > horario_inicio),
  check (periodo_fim is null or periodo_inicio is null or periodo_fim >= periodo_inicio)
);

create table if not exists turma_componentes_docentes (
  id bigint generated by default as identity primary key,
  turma_id bigint not null references turmas(id) on delete cascade,
  componente_id bigint not null references componentes_curriculares(id),
  docente_id bigint references docentes(id),
  carga_horaria integer not null check (carga_horaria > 0)
);

create index if not exists idx_tipos_curso_nivel on tipos_curso(nivel_id);
create index if not exists idx_cursos_tipo on cursos(tipo_curso_id);
create index if not exists idx_turmas_curso on turmas(curso_id);
create index if not exists idx_turma_componentes_turma on turma_componentes_docentes(turma_id);
create index if not exists idx_turma_componentes_docente on turma_componentes_docentes(docente_id);
create unique index if not exists uq_turma_componente_docente
  on turma_componentes_docentes (turma_id, componente_id, coalesce(docente_id, 0));

create or replace view vw_oferta_academica as
select
  t.id as turma_id,
  t.codigo as turma_codigo,
  n.nome as nivel,
  tc.nome as tipo_curso,
  c.nome as curso,
  t.carga_horaria as carga_horaria_curso,
  t.turno,
  t.situacao,
  t.horario_inicio,
  t.horario_fim,
  t.periodo_inicio,
  t.periodo_fim,
  d.nome as docente,
  cc.sigla,
  cc.nome as componente_curricular,
  tcd.carga_horaria as carga_horaria_componente
from turma_componentes_docentes tcd
join turmas t on t.id = tcd.turma_id
join cursos c on c.id = t.curso_id
join tipos_curso tc on tc.id = c.tipo_curso_id
join niveis n on n.id = tc.nivel_id
join componentes_curriculares cc on cc.id = tcd.componente_id
left join docentes d on d.id = tcd.docente_id;

create table if not exists ambientes (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nome text not null,
  status text not null default 'Disponível'
);

alter table docentes add column if not exists registro text unique;
alter table docentes add column if not exists area text;
alter table turmas add column if not exists nome text not null default '';

grant usage on schema public to service_role;
grant select, insert, update, delete on table public.ambientes, public.alocacoes_ambiente, public.turma_componentes_docentes, public.sugestoes_manutencao to service_role;
grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;